apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-7ysz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-7ysz
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-7ysz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-7ysz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-7ysz
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-pyxis-tenant/appstudio/dc-metro-map-7ysz@sha256:edbb9acb19c0fefbc5ae878385b7a4b6fbcd0aa834afb423c4c7ae27a7190b73
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
